apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api
    app: sample-api
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "sample-api"
    tags.datadoghq.com/version: "0.1.0"
  name: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    io.kompose.service: api
