apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    # Datadog autodiscovery annotations for nginx monitoring
    com.datadoghq.ad.check_names: '["nginx"]'
    com.datadoghq.ad.init_configs: '[{}]'
    com.datadoghq.ad.instances: '[{"nginx_status_url": "http://%%host%%:81/nginx_status"}]'
    com.datadoghq.ad.logs: '[{"source": "nginx", "service": "sample-nginx"}]'
  labels:
    io.kompose.service: nginx
    app: sample-nginx
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "sample-nginx"
    tags.datadoghq.com/version: "0.1.0"
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      annotations:
        # Datadog autodiscovery annotations for this pod
        ad.datadoghq.com/sample-nginx.check_names: '["nginx"]'
        ad.datadoghq.com/sample-nginx.init_configs: '[{}]'
        ad.datadoghq.com/sample-nginx.instances: '[{"nginx_status_url": "http://%%host%%:81/nginx_status"}]'
        ad.datadoghq.com/sample-nginx.logs: '[{"source": "nginx", "service": "sample-nginx", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern": "\\d{4}[-/]\\d{2}[-/]\\d{2}"}]}]'
      labels:
        io.kompose.service: nginx
        app: sample-nginx
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "sample-nginx"
        tags.datadoghq.com/version: "0.1.0"
    spec:
      containers:
        - name: sample-nginx
          image: sample-nginx:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
            - containerPort: 81
              protocol: TCP
              name: status
          env:
            # Datadog configuration
            - name: DD_ENV
              value: "dev"
            - name: DD_SERVICE
              value: "sample-nginx"
            - name: DD_VERSION
              value: "0.1.0"
            - name: DD_AGENT_HOST
              value: "datadog-agent"
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
          # Resource limits
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          # Mount nginx configuration
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-cm0
              readOnly: true
              subPath: nginx.conf
      restartPolicy: Always
      volumes:
        - name: nginx-cm0
          configMap:
            name: nginx-cm0
            items:
              - key: nginx.conf
                path: nginx.conf
