apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    # Enable Single Step APM instrumentation
    admission.datadoghq.com/enabled: "true"
  labels:
    io.kompose.service: nodejs-api
    app: nodejs-api
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "nodejs-api"
    tags.datadoghq.com/version: "0.1.0"
  name: nodejs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs-api
  template:
    metadata:
      annotations:
        # Enable Single Step APM instrumentation at pod level
        admission.datadoghq.com/enabled: "true"
        # Specify which container to instrument
        admission.datadoghq.com/nodejs-lib.version: "latest"
      labels:
        io.kompose.service: nodejs-api
        app: nodejs-api
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "nodejs-api"
        tags.datadoghq.com/version: "0.1.0"
    spec:
      containers:
        - name: nodejs-api
          image: nodejs-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            # Datadog configuration
            - name: DD_ENV
              value: "dev"
            - name: DD_SERVICE
              value: "nodejs-api"
            - name: DD_VERSION
              value: "0.1.0"
            - name: DD_AGENT_HOST
              value: "datadog-agent"
            - name: DD_TRACE_AGENT_URL
              value: "http://datadog-agent:8126"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_STARTUP_LOGS
              value: "true"
            # Enable APM
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            # Node.js specific
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
          # Resource limits and requests
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always
